name: Build and Test Code
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Build_And_Test:
    environment:
      name: Testing
    env:
      DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}}
      DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
      DATABASE_NAME: ${{secrets.DATABASE_NAME}}
      DATABASE_HOST: ${{secrets.DATABASE_HOST}}
      DATABASE_PORT: ${{secrets.DATABASE_PORT}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      ALGORITHM: ${{secrets.ALGORITHM}}
      ACCESS_TOKEN_EXPIRY_TIME: ${{secrets.ACCESS_TOKEN_EXPIRY_TIME}}
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
          POSTGRES_DB: ${{secrets.DATABASE_NAME}}_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v4
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Update Pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install pytest and coverage dependencies
        run: |
          pip install pytest pytest-cov
      - name: Run pytest with coverage and check threshold
        run: |
          pytest --cov=app/routers --cov-report=html && coverage report --fail-under=80
      - name: Run pylint on python files
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pylint . || true
      
    