name:   Build and Test Code
on: [push]
jobs:
    job1:
        runs-on:    ubuntu-latest
        steps:
            - name: pulling git repo
              uses: actions/checkout@v4
            - name: hello buddy
              run: echo "hello bro"